### ISSUE TITLE
Need to manage the machine being offline

### ISSUE THREAD

**Issue by Whytey** [Whytey/pymoebot#1]
https://github.com/Whytey/pymoebot/blob/b42ed9aabb68b104a0545021880ab07e7afcf6be/pymoebot/__init__.py#L54

`tinytuya` Err 905.

**Comment by Whytey** [comment]
And other errors from `tinytuya`:

2022-05-25 18:22:34,371 pymoebot - ERROR:Error from device: {'Error': 'Unexpected Payload from Device', 'Err': '904', 'Payload': None}
Traceback (most recent call last):
  File "/home/djwhyte/workspace/pymoebot/examples/sniffer/sniffer.py", line 44, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "/home/djwhyte/workspace/pymoebot/examples/sniffer/sniffer.py", line 40, in main
    await moebot.listen()
  File "/home/djwhyte/workspace/pymoebot/pymoebot/__init__.py", line 57, in listen
    self.__parse_payload(data)
  File "/home/djwhyte/workspace/pymoebot/pymoebot/__init__.py", line 33, in __parse_payload
    dps = data['dps']
KeyError: 'dps'

**Comment by Whytey** [comment]
```
2022-05-26 18:18:13,781 pymoebot - ERROR:Error from device: {'Error': 'Invalid JSON Response from Device', 'Err': '900', 'Payload': ''}
Traceback (most recent call last):
  File "/home/djwhyte/workspace/pymoebot/examples/sniffer/sniffer.py", line 44, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "/home/djwhyte/workspace/pymoebot/examples/sniffer/sniffer.py", line 40, in main
    await moebot.listen()
  File "/home/djwhyte/workspace/pymoebot/pymoebot/__init__.py", line 57, in listen
    self.__parse_payload(data)
  File "/home/djwhyte/workspace/pymoebot/pymoebot/__init__.py", line 33, in __parse_payload
    dps = data['dps']
KeyError: 'dps'
```
